### PR TITLE
Mention bencode format support in readme

### PR DESCRIPTION
**Pull request by casey**
Bendy, a bencode encoder and decoder, recently added feature-complete
serde support, so I thought it would be good to mention it in the
supported formats list.

### CODE REVIEW

**Comment by casey** [comment]
I'm not sure if this repo is being watched, so ping @dtolnay

**Comment by casey** [comment]
I landed https://github.com/P3KI/bendy/pull/42, which adds serde docs to both the readme, and enables serde on the docs.rs build, which will eventually make the serde module and associated docs start building, but it will probably be a little while before a new release is cut and the new docs.rs docs go live.

**Comment by dtolnay** [comment]
Thanks for following up.

It looks like there is supposed to be example code in https://docs.rs/bendy/0.3.2/bendy/serde/index.html#example-representations but it's cut off.

**Comment by casey** [comment]
Ah, thanks for checking that! I opened a PR to fix it, I'll ping this issue again when there's a release that includes the example code.

**Comment by casey** [comment]
@dtolnay This should be ready to go, a new version of bendy has been released with updated documentation that shows how to use the Serde integration, along with how Serde values are represented in bencode:

https://docs.rs/bendy/0.3.3/bendy/serde/index.html#example-representations

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
