### PR TITLE
Document #[serde(tag)] on struct structs

### PR DESCRIPTION
**Pull request by jplatte**
fixes https://github.com/serde-rs/serde/issues/1684

### CODE REVIEW

**Comment by jplatte** [comment]
ping @dtolnay

**Comment by zeenix** [comment]
@dtolnay ping or in general. I'd suggest just merging it cause it's trivial and having this docs is better than not having it so we don't need to be picky.

**Comment by magurotuna** [comment]
This is exactly what I was looking for. If this had been documented it would have saved my time a lot.
@dtolnay I'd be more than happy if this PR got merged and published. Do you see any issues in this PR that prevent you from merging it?

**Comment by jplatte** [comment]
Hey @dtolnay, could you please take a look?

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
